drop table group_posts;
drop table group_users;
drop table messageapprovals;
drop table postshares;
drop table sharedfiles;
drop table posts;
drop table groups;
drop table user_role;
drop table userprofiles;